#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-flavours amd64 \
    --binary-images iso-hybrid \
    --iso-application "Jukebox Arcade OS" \
    --iso-publisher "Jukebox Embedded Project" \
    --iso-volume "JUKEBOX_OS" \
    --bootappend-live "boot=live components quiet splash loglevel=3 vt.global_cursor_default=0 console=tty3 rd.systemd.show_status=false rd.udev.log_level=3 username=jukebox hostname=jukebox" \
    --apt-recommends false \
    --security false \
    --firmware-binary false \
    --firmware-chroot false \
    --compression xz \
    "$@"
